# Generated by Django 5.2.1 on 2025-06-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0015_alter_lead_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('user_hangup', 'User hangup'), ('agent_hangup', 'Agent hangup'), ('call_transfer', 'Call transferred'), ('voicemail_reached', 'Voicemail reached'), ('inactivity', 'Inactivity timeout'), ('machine_detected', 'Machine detected'), ('max_duration_reached', 'Max duration reached'), ('concurrency_limit_reached', 'Concurrency limit reached'), ('no_valid_payment', 'No valid payment'), ('scam_detected', 'Scam detected'), ('error_inbound_webhook', 'Inbound webhook error'), ('dial_busy', 'Dial busy'), ('dial_failed', 'Dial failed'), ('dial_no_answer', 'Dial no answer'), ('error_llm_websocket_open', 'LLM websocket open error'), ('error_llm_websocket_lost_connection', 'LLM websocket lost'), ('error_llm_websocket_runtime', 'LLM websocket runtime error'), ('error_llm_websocket_corrupt_payload', 'LLM corrupt payload'), ('error_no_audio_received', 'No audio received'), ('error_asr', 'ASR error'), ('error_retell', 'Retell internal error'), ('error_unknown', 'Unknown error'), ('error_user_not_joined', 'User didnâ€™t join web call'), ('registered_call_timeout', 'Registered call timeout')], help_text='Detailed Retell call outcome', max_length=50, null=True),
        ),
    ]
